/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(square_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(564ef3b60df7943576ae3a622857abe3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <howto/square_ff.h>
// pydoc.h is automatically generated in the build directory
#include <square_ff_pydoc.h>

void bind_square_ff(py::module& m)
{

    using square_ff    = gr::howto::square_ff;


    py::class_<square_ff,
        gr::block,
        gr::basic_block,
        std::shared_ptr<square_ff>>(m, "square_ff", D(square_ff))

        .def(py::init(&square_ff::make),
           D(square_ff,make)
        )
        



        ;




}








