/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(litexgnu.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0170876b721e6cd8f4e07bdb87d6eea3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <litexgnu/litexgnu.h>
// pydoc.h is automatically generated in the build directory
#include <litexgnu_pydoc.h>

void bind_litexgnu(py::module& m)
{

    using litexgnu    = gr::litexgnu::litexgnu;


    py::class_<litexgnu,
        gr::block,
        gr::basic_block,
        std::shared_ptr<litexgnu>>(m, "litexgnu", D(litexgnu))

        .def(py::init(&litexgnu::make),
           D(litexgnu,make)
        )
        



        ;




}








